# Site settings
title: Gregory Malecha
email: gmalecha@gmail.com
url: https://gmalecha.github.io
hostname: gmalecha.github.io
synopsis: >
  Mullings on computer science and math: programming languages, compilers, and program analysis.
description:
  I do research on programming languages, program verification, compilers, and program analysis.
skills: "Programming Languages - Program Verification - Static Analysis - Compilers"
meta_author: Gregory Malecha


# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: gregorymalecha

# Color settings (hex-codes without the leading hash-tag)
color:
  accent: 6C7EE4
  dark-primary: 455A64
  primary: 607D8B
  light-primary: CFD8DC
  text: FFFFFF
  primary-text: 212121
  secondary-text: 727272
  divider-color: B6B6B6

collections:
  publications:
    output: true
    permalink: /publications/:title
    section_url: publications
  posts:
    output: true
    permalink: /reflections/:year/:title
    section_url: publications

defaults:
- scope:
    path: ""
    type: publications
  values:
    layout: publication
    section: Publications
    section_dir: publications
- scope:
    path: "publications"
  values:
    section: Publications
    section_dir: publications
- scope:
    path: ""
    type: posts
  values:
    layouts: post
    section: Reflections
    section_dir: reflections
- scope:
    path: "reflections"
  values:
    section: Reflections
    section_dir: reflections
- scope:
    path: "projects"
  values:
    section: Projects
    section_dir: projects

# Footer settings
footer:
  copyright: Gregory Malecha

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/gmalecha
  - title: twitter
    url: https://twitter.com/gregory_malecha
  - title: google-plus
    url: https://plus.google.com/+GregoryMalecha

# Build settings
markdown: kramdown
markdown_ext: md, markdown
kramdown:
  extensions: ["footnotes", "no_intra_emphasis", "fenced_code_blocks"]
  highlighter: pygmentize
permalink: pretty

projects:
  - title: Mirror Core
    descr: >
      MirrorCore is a framework for easing the burden of building reflective automation in Coq proof assistant.
    url: https://github.com/gmalecha/mirror-core
  - title: ExtLib
    descr: >
      ExtLib is an extension to Coq's standard library which embraces new features such as universe polymorphism, primitive projections, and type classes.
    url: https://github.com/coq-ext-lib/coq-ext-lib
  - title: Template-Coq
    descr: >
      Template-Coq is a bare-bones quoting library for Coq. Its syntax is designed to be as close as possible to Coq's internal representation.
    url: https://github.com/gmalecha/template-coq
  - title: VeriDrone
    descr: >
      VeriDrone is exploring foundational verification of cyber-physical
      systems such as quadcopters. Check us out!
    url: http://veridrone.ucsd.edu/
