# Site settings
title: Gregory Malecha
email: gmalecha@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I do research on program verification, compilers, and program analysis.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://gmalecha.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
